[package]
name = "ores-common-desktop-infra"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/platform_lib.rs"

[dependencies]
ores-runtime-generation = { path = "../../runtime-generation/rust" }
serde.workspace = true
thiserror.workspace = true
